update_configs:
    - automerged_updates:
          - match:
                update_type: all
                dependency_type: production
          - match:
                update_type: all
                dependency_type: development
      directory: "/"
      package_manager: javascript
      update_schedule: weekly
