version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                  name: install
                  command: yarn install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: build
                command: yarn run release
            - run:
                name: test
                command: yarn run test:coverage
            - run:
                name: e2e
                command: yarn run test:e2e
            - run:
                name: codecov
                command: yarn run codecov
